### PR TITLE
Feat: Added the mentorship  section as decided  issue#210

### PR DESCRIPTION
**Pull request by vashujoshi**
Finally done with the mentorship section
created separate file which can be accessed by here

image
 

> created separate html and css for mentor section.
> this is how it looks 

image

### CODE REVIEW

**Comment by vashujoshi** [comment]
@Rizwan102003 @pulkitpathak99 @SaurabhS55 @arushi2610  have a look and merge this plz as fast as you can .
And label it under the tags gsoc ext,hacktober open,level 2-3

**Review by Rizwan102003 — APPROVED** [review]
looks good

**Comment by Rizwan102003** [comment]
@SaurabhS55 @pulkitpathak99 please put the labels here before I merge

**Comment by vashujoshi** [comment]
@Rizwan102003 bro labels aap he daaldo plz before merging ya PR aab count nhi hoga bina label KE?

**Pull request merged**
