### PR TITLE
Navbar Changes

### PR DESCRIPTION
**Pull request by dipeshkumar799**
in this project ,i have to change navbar, i make the navbar sticky and also change some background color and i also change list view while hovering on list the list size will increase also change bg-colors 

https://github.com/user-attachments/assets/f3ca6679-796d-4609-afc9-ecd3546884ec

@Code-Social :pls review my code
#245

### CODE REVIEW

**Comment by SaurabhS55** [comment]
what is your issue number?

**Comment by dipeshkumar799** [comment]
My issue no. #245

**Comment by Rizwan102003** [comment]
@dipeshkumar799 the dark mode switch broke in the navbar in your pr. Please look into it once.

**Comment by dipeshkumar799** [comment]
@Rizwan102003  ok brother i will fixed it tonight

**Comment by dipeshkumar799** [comment]
@Rizwan102003 : brother  it is not broke .it is image orr icon issue

**Comment by Rizwan102003** [comment]
yeah i know,can u fix it?

**Comment by dipeshkumar799** [comment]
@Rizwan102003  ok I will try at tonight ☺️

**Pull request merged**
