### PR TITLE
 The re-design of the components and the the script js file was updated here .

### PR DESCRIPTION
**Pull request by shitcodebykaushik**
This is the updated version of the who src file .

### CODE REVIEW

**Comment by shitcodebykaushik** [comment]
This is the final submisiion . Kindky review the whole code from the re-design repo then try to merge it  .

**Comment by SaurabhS55** [comment]
Could you share screenshots of the changes?

**Comment by shitcodebykaushik** [comment]
Sure bro . but the things is you can simple go into the my branch and run the project from your end to . Overall by tonight I will submit the screenshot of the most project.

**Comment by arushi2610** [comment]
This branch has merge conflicts, kindly solve them, and then I'll merge.

**Pull request closed without merging**
