### PR TITLE
added event calendar and dark mode on the top right corner

### PR DESCRIPTION
**Pull request by GauriSachan**
#36
please add the labels of level2, gssoc-ext and hacktoberfest before closing this pr
image
image
image

### CODE REVIEW

**Comment by pulkitpathak99** [comment]
@arushi2610 @Rizwan102003

**Comment by GauriSachan** [comment]
> @arushi2610 @Rizwan102003

please mark it as done and the issue also

**Comment by Rizwan102003** [comment]
Can you make the calendar more visually appealing such that its bigger and the event names fit inside nicely?

**Comment by GauriSachan** [comment]
> Can you make the calendar more visually appealing such that its bigger and the event names fit inside nicely?

ok
but will have to open another pull request so can you close this on?

**Comment by GauriSachan** [comment]
> Can you make the calendar more visually appealing such that its bigger and the event names fit inside nicely?

done

**Comment by GauriSachan** [comment]
image

**Comment by arushi2610** [comment]
Add event option should only be available to the developers, not everyone.

**Comment by GauriSachan** [comment]
> Add event option should only be available to the developers, not everyone.

I took your request into consideration and added a popup which verifies whether we are a developer or not by asking our password 
image
for now the password is : devpassword but you can change it in the code later on only those who give the correct password will be allowed to change the calendar

**Comment by GauriSachan** [comment]
> > Add event option should only be available to the developers, not everyone.
> 
> I took your request into consideration and added a popup which verifies whether we are a developer or not by asking our password image for now the password is : devpassword but you can change it in the code later on only those who give the correct password will be allowed to change the calendar

for example here i entered the wrong password and i can only view the calendar 
image
but if i had entered the correct password then i would have been able to edit it
image
image

**Comment by arushi2610** [comment]
Looks good! can make more changes going forward.

**Pull request merged**
