### PR TITLE
Improved navbar responsiveness and dropdown alignment

### PR DESCRIPTION
**Pull request by Aayush-Roy**
- Added media queries for better mobile support, including hamburger menu toggle
- Fixed dropdown alignment to ensure it appears below the parent item
- Enhanced overall layout to ensure a more user-friendly experience across screen sizes

### CODE REVIEW

**Comment by Aayush-Roy** [comment]
Improved navbar responsiveness and dropdown alignment

- Added media queries for better mobile support, including hamburger menu toggle
- Fixed dropdown alignment to ensure it appears below the parent item
- Enhanced overall layout to ensure a more user-friendly experience across screen sizes

**Comment by pulkitpathak99** [comment]
Can you share the screenshot of the changes that you have made?

**Comment by Aayush-Roy** [comment]
Sure, here it is

**Comment by Aayush-Roy** [comment]
Screenshot 2024-10-04 192558

**Comment by SaurabhS55** [comment]
I will assign this issue to you. Do following changes:
1. Pull recent changes.
2. make home page responsive.
3. also fix dropdown alignment.
image
4. and also remove top padding

**Comment by Aayush-Roy** [comment]
I accept the assignment.

**Comment by Aayush-Roy** [comment]
Added Hamburger Menu for Mobile View: Implemented a responsive hamburger menu that appears when the screen width is less than 768px. The menu can toggle the visibility of the navigation links on mobile devices.

Responsive Navigation: Updated the navbar styling to ensure that it adapts to smaller screens by stacking vertically and hiding the dropdown links until the hamburger menu is clicked.

Dropdown Menu Fix: Adjusted the alignment and functionality of the dropdown menu to ensure it works seamlessly in both desktop and mobile views.

JavaScript for Toggle: Added a simple JavaScript function to toggle the active class on the navigation menu when the hamburger icon is clicked, improving user interaction on smaller screens.

**Comment by Aayush-Roy** [comment]
Screenshot 2024-10-05 160746

**Comment by SaurabhS55** [comment]
@Aayush-Roy Can you create new branch of your features and then push your
 changes?

**Comment by arushi2610** [comment]
@SaurabhS55 you can merge this PR when it's done.

**Comment by SaurabhS55** [comment]
@Aayush-Roy can you resolve this merge conflicts. once you done then ping here I will merge this pr.

**Comment by SaurabhS55** [comment]
firstly pull all changes and then resolve conflicts.

**Pull request closed without merging**
