### PR TITLE
feat: added navbar and footer to Resources.html

### PR DESCRIPTION
**Pull request by Naga-Himaja**
Added navbar and footer, which also now supports dark and light mode switch

Screenshots:

https://github.com/user-attachments/assets/28d7d813-9245-437c-a53c-bbb989db7d5a

OS [macOS]
Browser [Chrome]

### CODE REVIEW

**Comment by Naga-Himaja** [comment]
Closes #381 
Reviewers: @Rizwan102003 @pulkitpathak99

**Comment by arushi2610** [comment]
Kindly add screenshots along with your PR.

**Comment by Naga-Himaja** [comment]
> Kindly add screenshots along with your PR.

Done. Please check it now

**Comment by Naga-Himaja** [comment]
@Rizwan102003 Can you please check this PR?

**Review by Rizwan102003 — APPROVED** [review]

**Pull request merged**
