### PR TITLE
Improve homepage layout and style : Adjust hero image size, enhance feature sect…

### PR DESCRIPTION
**Pull request by ManishGupta2003**
…ion styling, and update responsive design.

### Description of Changes:
- **Hero Image**: Adjusted the hero image size to prevent it from covering the entire space, ensuring a better visual balance on the homepage.
- **Feature Section Styling**: Enhanced the styling of the features section, including improved spacing and alignment to create a cleaner layout.
- **Responsive Design Improvements**: Updated media queries to ensure better display on smaller screens, making the navigation and content more user-friendly.
- **General Aesthetics**: Made minor adjustments to colors, fonts, and paddings to enhance the overall aesthetics of the homepage.

These changes contribute to a more visually appealing and user-friendly experience for visitors.

### CODE REVIEW

**Comment by SaurabhS55** [comment]
can you share screenshot of those changes?

**Comment by arushi2610** [comment]
I don't think those images are relevant or required for now.

**Comment by ManishGupta2003** [comment]
05 10 2024_13 05 43_REC

**Comment by ManishGupta2003** [comment]
05 10 2024_13 06 56_REC

**Comment by ManishGupta2003** [comment]
can you recheck the  ui . I enhance the frontend ui/ux

**Comment by ManishGupta2003** [comment]
can you recheck the ui . I enhance and fix the frontend ui/ux
________________________________

**Pull request closed without merging**
