### PR TITLE
Added Learning section

### LINKED ISSUE #18: Create Learn section
I would like to create a learn section where they can learn different courses.Please assign me under gssoc.

### PR DESCRIPTION
**Pull request by pavitraag**
Closes #18 

image
image
image

### CODE REVIEW

**Comment by pavitraag** [comment]
@Rizwan102003 @arushi2610 Can u please do the reviews

**Comment by pavitraag** [comment]
@SaurabhS55 hey can u please look into the reviews

**Comment by SaurabhS55** [comment]
@Rizwan102003 @arushi2610 can you plzz review this pr once?

**Review by Rizwan102003 — COMMENTED** [review]
looks good.PR merged.

**Pull request merged**
