### PR TITLE
[ADDED] Feature: Adding a book tickets page for live events #350

### PR DESCRIPTION
**Pull request by KrishPatel1205**
# Related Feature:
- #350 

Fixed issue #350

## Description
When the user goes to the live event option there was no option for and live events, I fixed this by adding a new webpage for booking your tickets.

## Screenshots / Videos:
Screenshot 2024-10-22 at 8 31 29 PM

https://github.com/user-attachments/assets/d9973920-c3e3-457b-b3ec-b74cddacf18e

### CODE REVIEW

**Comment by KrishPatel1205** [comment]
It would be great if you could assign this the level 3 tag, Thank you!

**Comment by Rizwan102003** [comment]
@KrishPatel1205 we do not currently need this feature. Can you make a registrations page for virtual events? In  the navbar there is a live events sections. Hovering over it shows the name of live ongoing events. Clicking on them should redirect the user to a registration page containing the details of the event along with the registration button. Clicking on the registration button should open a dialogue box where the user can put his name and email.

**Comment by KrishPatel1205** [comment]
> @KrishPatel1205 we do not currently need this feature. Can you make a registrations page for virtual events? In the navbar there is a live events sections. Hovering over it shows the name of live ongoing events. Clicking on them should redirect the user to a registration page containing the details of the event along with the registration button. Clicking on the registration button should open a dialogue box where the user can put his name and email.

I have completed this and you can check it out at #364

**Comment by arushi2610** [comment]
It's resolved so I'm closing this PR.

**Pull request closed without merging**
