### PR TITLE
Event Calendar Section, Forum/Discussion Boards, Footer Structure #234

### PR DESCRIPTION
**Pull request by Prerrna**
#234 Is your feature request related to a problem? Please describe.
I'm always frustrated when users cannot easily find information about upcoming events and community discussions on our website, leading to reduced engagement and missed opportunities.

Describe the solution you'd like
I would like to implement an "Upcoming Events" section on the homepage that clearly showcases our events, workshops, and meetups. Each event should include a title, date, time, location, and a registration link to make it easy for users to participate. Additionally, the Forum/Discussion Boards section should be repositioned to the footer for better visibility, encouraging users to engage in community discussions. This section should still include links to both our dedicated forum page and a third-party Discourse community, fostering greater interaction among members.

Describe alternatives you've considered
I considered keeping the Forum section in the main content area but found that moving it to the footer enhances the overall layout and highlights it as a resource for community engagement. Other alternatives included creating a separate events page, but I believe having it directly on the homepage increases visibility and participation.

Additional context
The "Upcoming Events" section will help users quickly find relevant activities and encourage them to engage with our community. By placing the Forum/Discussion Boards in the footer, we maintain a clean design while ensuring users can easily find ways to interact with others. This adjustment also includes keeping the copyright statement at the bottom for clarity. Screenshots of the new layout can be provided upon request for further illustration.
Screenshot 2024-10-15 at 12 42 03 PM
Screenshot 2024-10-15 at 12 41 37 PM

### CODE REVIEW

**Comment by Prerrna** [comment]
Please add lables Gssoc extd24 and hacktoberfest

**Comment by Prerrna** [comment]
Also i want to go ahead and add more stuff like Member Profiles , dark mode etc. it would be great if you assign me

**Comment by SaurabhS55** [comment]
what is you issue number

**Comment by SaurabhS55** [comment]
@Prerrna You have made changes directly in main branch. kindly create new branch for your features. and then push it.

**Comment by Prerrna** [comment]
i want to edit changes ... why have you closed??

**Comment by Prerrna** [comment]
is it good now?

**Comment by Prerrna** [comment]
@SaurabhS55 do i need to do anything else ?

**Comment by arushi2610** [comment]
@SaurabhS55 please check.

**Comment by SaurabhS55** [comment]
@Prerrna plzz resolve merge conflicts.

**Comment by Prerrna** [comment]
okay

**Pull request closed without merging**
