### PR TITLE
change the theme toogle button with modern style button

### PR DESCRIPTION
**Pull request by REHAN-18**
issue #402 
Redesign the toggle button with minimal  modern style 
before --
Screenshot 2024-10-25 at 9 19 20 PM

after --
Screenshot 2024-10-25 at 9 17 23 PM
 @protonerdy see this & merge it !!! 
@arushi2610

### CODE REVIEW

**Comment by REHAN-18** [comment]
@pulkitpathak99 @Rizwan102003 sir pls see this & merge issue #402

**Review by Rizwan102003 — COMMENTED** [review]
I feel like the current light/dark button looks better than this one. @arushi2610 what do you think?

**Comment by REHAN-18** [comment]
@Rizwan102003 bro but i have assign this work and i done my work 🥲

**Comment by REHAN-18** [comment]
@Rizwan102003 @arushi2610 pls see this I ve done this with hardwork pls merge it!!🥹

**Comment by Rizwan102003** [comment]
@REHAN-18 the desicion lies on the sole discretion of @arushi2610 . We will follow the theme she decides.

**Comment by arushi2610** [comment]
@REHAN-18 keep the same font-size as we had before and decrease the size of the toggle button. @Rizwan102003 we can merge it after this change. New toggle button also matches the theme.

**Comment by REHAN-18** [comment]
@arushi2610  the font size is the same but in  pics I send u  is zoomed so that the font is looking big & the toogle size is decent enough... if you want to decrease the size of toggle I will do it

**Comment by REHAN-18** [comment]
@arushi2610 the toggle size is looking decent according to navbar its suit if you want then tell me???

**Comment by arushi2610** [comment]
Merged the PR, great work!

**Comment by REHAN-18** [comment]
@arushi2610 ma'am gssoc level 2 label??

**Comment by REHAN-18** [comment]
> Merged the PR, great work!

@arushi2610 thanks ma'am but what about gssoc ext label can you give me level 2 ......🥲

**Comment by REHAN-18** [comment]
> Merged the PR, great work!

@arushi2610 @Rizwan102003 pls give me level label

**Comment by REHAN-18** [comment]
@arushi2610 maam u missed to give level label pls give me level 2 🥲

**Comment by REHAN-18** [comment]
@Rizwan102003 thanks sir 😇

**Comment by protonerdy** [comment]
Good work!

**Comment by REHAN-18** [comment]
@protonerdy @arushi2610 @Rizwan102003 can I join your organisation #Code Social

**Comment by arushi2610** [comment]
You can apply [here](https://forms.gle/zDakdQL8ixrVusUU9)

**Comment by REHAN-18** [comment]
> You can apply [here](https://forms.gle/zDakdQL8ixrVusUU9)

@arushi2610 applied ma'am !!!

**Pull request merged**
