### PR TITLE
fix: correct image loading for toggle button in light/dark mode

### PR DESCRIPTION
**Pull request by Naga-Himaja**
Reviewers: @SaurabhS55 @pulkitpathak99

### CODE REVIEW

**Comment by pulkitpathak99** [comment]
Can you try to correct it again?

**Comment by Naga-Himaja** [comment]
> Can you try to correct it again?

I didn't quite understand what you meant. Can you please be specific?

**Comment by pulkitpathak99** [comment]
The toggle button image is still not loading, even after your merge. Try to correct this issue!

**Comment by Naga-Himaja** [comment]
> The toggle button image for ligh/dark mode is still not loading, even after your merge. Try to correct this issue!

I just opened the link and I can clearly see the image. 
Screenshot 2024-10-20 at 3 46 47 AM
Screenshot 2024-10-20 at 3 47 10 AM

**Comment by Naga-Himaja** [comment]
I would recommend clearing the cache, or hard refresh. I think that should work.

**Pull request merged**
