### PR TITLE
Added a trailing cursor effect for enhanced user interaction

### PR DESCRIPTION
**Pull request by akhulisumit**
#326 

This pull request introduces a trailing cursor effect to improve user interaction and create a more dynamic interface. The effect follows the user's mouse movement, providing a visually engaging experience that complements the overall design.

https://github.com/user-attachments/assets/0e84bc1a-c65e-4f1b-9d09-b566a77e04bf

### CODE REVIEW

**Review by Rizwan102003 — APPROVED** [review]

**Comment by Rizwan102003** [comment]
@akhulisumit what is your issue number? @arushi2610 do we need this?

**Comment by arushi2610** [comment]
Yea, let's do it. @akhulisumit make the cursor movement smooth. And add a video for demonstration.

**Comment by pulkitpathak99** [comment]
@Rizwan102003 @arushi2610 It's ready to be merged now. I have assigned the labels

**Comment by akhulisumit** [comment]
Because of the fast movement of the cursor and video recording quality, you might have to face the issue. I optimized the smoothness as much as possible. You can please check out he video and use it once and let me know if you face any issue. I will be very happy to help.

https://github.com/user-attachments/assets/a754d1bf-785f-404e-99a6-c4bfa878671d

**Comment by akhulisumit** [comment]
Btw I liked your repo and would like to contribute more and make it better

**Review by Rizwan102003 — COMMENTED** [review]
This looks fun tbh😂💯

**Comment by Rizwan102003** [comment]
Feel free to create more issues and contribute @akhulisumit

**Comment by akhulisumit** [comment]
BTW your repo is good and I would like to make more contributions

**Pull request merged**
