### PR TITLE
update new scroll button

### PR DESCRIPTION
**Pull request by ak-0283**
update new scroll button 

Screenshot 2024-10-16 195132

### CODE REVIEW

**Comment by SaurabhS55** [comment]
what is your issue number?

**Comment by ak-0283** [comment]
Sry,

I don't know know about how to contribute as a open source project.now I got the idea that first check the issue then contribute 😞

**Comment by ak-0283** [comment]
My issue number is #256

**Comment by Rizwan102003** [comment]
@ak-0283 issue #256 was opened by another contributor. @SaurabhS55 is asking you the issue you created before making the pr.

**Comment by ak-0283** [comment]
Ok

**Pull request closed without merging**
