### PR TITLE
enhancement: added new navbar and footer pages that can be used across all pages

### LINKED ISSUE #413: enhancement: creating a separate html page for navbar and footer
**Problem**
The navbar is being enhanced by many contributors, and it is different on each page. It is not consistent across the website, and might effect user experience

**Solution**
Creating separate pages for navbar and footer, and loading those in each page using js

Reviewers: @arushi2610 @pulkitpathak99 @Rizwan102003

### PR DESCRIPTION
**Pull request by Naga-Himaja**
- Closes #413 

**Changes made**
- Added new navbar and footer pages
- common.js to load navbar and footer
- changes in darkmode.js to fix load issues
- added the changes only to index.html for the time being

**Screenshots**

https://github.com/user-attachments/assets/a1cbd636-0f83-46a0-9a04-1e352e6cfe12

### CODE REVIEW

**Comment by Naga-Himaja** [comment]
Reviewers: @Rizwan102003 @pulkitpathak99 @arushi2610 @SaurabhS55 
Please review it

**Comment by Rizwan102003** [comment]
@Naga-Himaja please resolve the conflicts.

**Comment by Naga-Himaja** [comment]
@Rizwan102003 there are no conflicts now. Can you please check it?

**Review by Rizwan102003 — APPROVED** [review]

**Comment by Rizwan102003** [comment]
@arushi2610 please review this once

**Comment by Naga-Himaja** [comment]
@Rizwan102003, correct me if I am wrong, but as the review is being delayed and other PRs are being merged, this PR is facing merge conflicts. Please tell me how I can proceed further with this PR. Thanks!

**Comment by Rizwan102003** [comment]
@Naga-Himaja you are right. That's why I try to advice everyone to use separate files for your code if you can,that way merge conflicts have a lesser chance to arise.

**Comment by Naga-Himaja** [comment]
> @Naga-Himaja you are right. That's why I try to advice everyone to use separate files for your code if you can,that way merge conflicts have a lesser chance to arise.

I get it, but in this case, it was necessary to make changes in the index file, since that is the starting point of the application. Can you please suggest any steps to be taken wrt this PR?

**Comment by Rizwan102003** [comment]
@Naga-Himaja yeah I understand the problem. In any way I suggest you work on other feature related issues(I will be making some new tomorrow, you can look into those) because design based prs would be approved from within the community and might not be accepted if the community members do not like it so feature based issues have a higher chance of getting accepted. @arushi2610 @SaurabhS55 @pulkitpathak99 @protonerdy what say?

**Comment by Naga-Himaja** [comment]
> @Naga-Himaja yeah I understand the problem. In any case I suggest you work on other feature related issues(I will be making some new tomorrow, you can look into those) because design based prs would be approved from within the community and might not be accepted if the community members do not like it so feature based issues have a higher chance of getting accepted. @arushi2610 @SaurabhS55 @pulkitpathak99 @protonerdy what say?

I understand. Sure. Should I keep this PR open for the time being, or close it?

**Comment by arushi2610** [comment]
> @Naga-Himaja yeah I understand the problem. In any case I suggest you work on other feature related issues(I will be making some new tomorrow, you can look into those) because design based prs would be approved from within the community and might not be accepted if the community members do not like it so feature based issues have a higher chance of getting accepted. @arushi2610 @SaurabhS55 @pulkitpathak99 @protonerdy what say?

I agree! Currently, the merge conflicts are bound to arise as there are many people working on the same repo. Especially on the design part. Kindly resolve the merge conflicts and your PR will be merged.

**Comment by Naga-Himaja** [comment]
@arushi2610 @pulkitpathak99 @Rizwan102003 I resolved the merge conflicts, can you please check now? Thanks!

**Review by Rizwan102003 — COMMENTED** [review]
merging it

**Comment by Rizwan102003** [comment]
@Naga-Himaja the navbar details were in white and could not be seen against the navbar box in day mode.please check it once

**Comment by Naga-Himaja** [comment]
> @Naga-Himaja the navbar details were in white and could not be seen against the navbar box in day mode.please check it once

Yeah, I just saw that. I will raise a new PR for it

**Comment by Naga-Himaja** [comment]
> @Naga-Himaja the navbar details were in white and could not be seen against the navbar box in day mode.please check it once

Hello @Rizwan102003,
I saw an issue addressing this issue. Can you please check it and assign me the issue. I found the fix, and waiting for the issue to be assigned to me

**Pull request merged**
