### PR TITLE
Fixed images not loading issue ! #222

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello, PR
Fixed issue number - #222

These four images(2 website logo, dark mode & light mode icon image) are not loading in Header & Footer, but now I fixed this issue properly -

https://github.com/user-attachments/assets/9dc4e8e1-abd2-495b-8f42-79f5fc381f7d

Screenshot 2024-10-15 221619
Screenshot 2024-10-15 221611
Screenshot 2024-10-15 221637

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@SaurabhS55 @pulkitpathak99 merge my pull request,

PA can I get level 2 for this issue ? because I solved the 4 images not loading issue....

**Comment by Rizwan102003** [comment]
@pulkitpathak99 please put the labels here before i merge it.

**Review by Rizwan102003 — APPROVED** [review]

**Comment by SaurabhS55** [comment]
@Rizwan102003 you can merge this.

**Review by Rizwan102003 — APPROVED** [review]
looking good

**Pull request merged**
