### PR TITLE
Created Site Map Page

### PR DESCRIPTION
**Pull request by VidhanThakur09**
Fixes:  #432 

# Description

This pull request introduces a comprehensive site map for the project. The site map includes links to all relevant pages and resources within the application. This will enhance user navigation and improve search engine optimization (SEO).

**Created a new file**: A new file named `sitemap.html` is created with all the styling and for styling `sitemap.css` is created. 

## How Has This Been Tested? ⚙️

The program was tested locally on a machine using the Chrome browser. To verify the changes, the website was loaded after the modifications were made. This involved manually inspecting the visual elements and functionally testing various user interactions to ensure the changes were implemented correctly.

# Screenshots / videos 

https://github.com/user-attachments/assets/dbcb625a-97a6-448f-b14d-9fa45ce39cd0

### CODE REVIEW

**Comment by VidhanThakur09** [comment]
@Rizwan102003  @arushi2610  please review this PR.

**Comment by VidhanThakur09** [comment]
@Rizwan102003 @arushi2610 i would be wonderful if you could review this issue

**Comment by VidhanThakur09** [comment]
@arushi2610 

I would appreciate it if you could kindly review this pull request.

Thank you.

**Comment by VidhanThakur09** [comment]
@Rizwan102003 please review this PR,

**Comment by Rizwan102003** [comment]
@VidhanThakur09 @arushi2610 will have the final say for this pr. She is currently preoccupied with some matters. Thank you for having patience. We will try to resolve this asap.

**Comment by VidhanThakur09** [comment]
I appreciate your time and thoughtful consideration regarding this matter.

**Comment by arushi2610** [comment]
@VidhanThakur09 please change the colors to match our color scheme. Then, we can merge the PR.

**Comment by VidhanThakur09** [comment]
@arushi2610 mam can you provide the colour pallets which is use in website color scheme.

**Comment by VidhanThakur09** [comment]
@arushi2610 fixed all the Improvement , please review this PR


https://github.com/user-attachments/assets/b625de90-1733-44f1-a49d-54bfbde9d5e4

**Comment by VidhanThakur09** [comment]
@Rizwan102003 @arushi2610 please review this PR.

**Pull request closed without merging**
