### PR TITLE
about-section-styling

### PR DESCRIPTION
**Pull request by aarch34**
I have added a background image and styled the about section so that it had a better user interface.
image

### CODE REVIEW

**Review by Rizwan102003 — APPROVED** [review]

**Comment by Rizwan102003** [comment]
@aarch34 do you have an issue number?

**Comment by aarch34** [comment]
issue 196

**Comment by aarch34** [comment]
thank youu!

**Comment by aarch34** [comment]
Hi Rizwan, did you mean to send this message? because I cant find anything on my github
    On Tuesday 22 October 2024 at 22:51:52 GMT+5:30, SK MD RIZWAN ***@***.***> wrote:  
 
 


@aarch34 your changes are not showing as expected on the website,please look into it once.

**Comment by Rizwan102003** [comment]
its fine its working now,no worries,thats why i deletd the comment

**Pull request merged**
