### PR TITLE
Added linktree for social media accounts

### PR DESCRIPTION
**Pull request by Kshitijasharma**

### CODE REVIEW

**Comment by Kshitijasharma** [comment]
@Rizwan102003 , hello
Can you check now?

**Review by Rizwan102003 — COMMENTED** [review]
please attach a screenshot of the change so that we can view it before merging

**Comment by Kshitijasharma** [comment]
Here are the changes.

https://github.com/user-attachments/assets/20876ba7-8ce6-4666-8ee8-87e43810cbe0

**Review by Rizwan102003 — CHANGES_REQUESTED** [review]
Remove whatsapp,reddit and add twitter and make sure all the links redirect to the community profiles

**Comment by Kshitijasharma** [comment]
https://github.com/user-attachments/assets/d7b47725-a1a6-4f0f-84d1-7ce5cc298bda

## can you review the changes?

**Comment by Rizwan102003** [comment]
@Kshitijasharma are all the buttons correctly redirecting to the community accounts? If you need any of the links, feel free to ask for them.

**Review by Rizwan102003 — APPROVED** [review]

**Comment by Rizwan102003** [comment]
thats fine for now,we'll add em later.

**Review by Rizwan102003 — APPROVED** [review]
lgtm

**Pull request merged**
