### PR TITLE
[feat]Allow Adding Multiple Events on a Single Date in Calendar

### PR DESCRIPTION
**Pull request by Saurabhchaudhary9799**
### Description :
This PR enhances the calendar functionality by enabling the addition and display of multiple events on a single date.

-fix issue #384 

### Type of change : 
-feature request 

### Screen Recording : 
[Screencast from 2024-10-25 00-28-58.webm](https://github.com/user-attachments/assets/42e2c5dc-56fc-4fcb-ac6f-a2b448ce84c3)

### CODE REVIEW

**Comment by Saurabhchaudhary9799** [comment]
@Rizwan102003 , Kindly check my PR.

**Comment by arushi2610** [comment]
Great work! Merging the PR.

**Comment by Saurabhchaudhary9799** [comment]
@arushi2610 , please add level3 label on this pr

**Review by Rizwan102003 — COMMENTED** [review]
labels added

**Pull request merged**
