### PR TITLE
the scroll to top button has been added to learning page

### LINKED ISSUE #461: learning page dosen't have scroll to top button
please assign me this issue under gssoc extd , hacktober fest 
and make it atleast level2 
i will also add the scroll to top button at other pages which comes under learning page

### PR DESCRIPTION
**Pull request by 2004pra**
i have completely added the scroll to top button to the learning page 
@arushi2610 
please make it level 2 please i haven't got any level 2 for so many days please mam 
it was an amazing experience contributing to your project mam.
fixes #461

### CODE REVIEW

**Comment by arushi2610** [comment]
Our mentors will be deciding the level @pulkitpathak99 @SaurabhS55.

**Comment by 2004pra** [comment]
Ok

**Review by Rizwan102003 — APPROVED** [review]
lgtm

**Comment by 2004pra** [comment]
why this pr is not merged yet please tell me .. 
@Rizwan102003 @pulkitpathak99 @arushi2610 @SaurabhS55

**Pull request merged**
