### PR TITLE
Chatbot Icon overlaps with Scroll to top button #421

### PR DESCRIPTION
**Pull request by sachinggsingh**
Chatbot Icon overlaps with Scroll to top button #421 has been solved

### CODE REVIEW

**Comment by Rizwan102003** [comment]
@sachinggsingh please attach a screenshot so we can see how it looks

**Review by Rizwan102003 — COMMENTED** [review]
we would like to see how it looks before merging it

**Comment by sachinggsingh** [comment]
ok i will provide before and after in the PR

**Comment by sachinggsingh** [comment]
**Before**
Screenshot 2024-10-30 143548
**After**
Screenshot 2024-10-30 143445

**Comment by sachinggsingh** [comment]
Thats how it looks now

**Comment by sachinggsingh** [comment]
i have provided in the comments

**Review by Rizwan102003 — APPROVED** [review]
lgtm

**Pull request merged**
