### PR TITLE
Updated Favicon in the website

### PR DESCRIPTION
**Pull request by BVPKARTHIKEYA**
Updatd Favicon in the web page!!
image

### CODE REVIEW

**Comment by SaurabhS55** [comment]
@BVPKARTHIKEYA favicon is not visible. Can you correct this mistake:
image
and push changes when it will visible

**Comment by BVPKARTHIKEYA** [comment]
Now favicon is visible!!
Hope you like it!!

**Comment by SaurabhS55** [comment]
> @BVPKARTHIKEYA favicon is not visible. Can you correct this mistake: image and push changes when it will visible

remove this extra head tag

**Comment by BVPKARTHIKEYA** [comment]
okay!! i will do the changes!!
can you show the output of my code after deploying!!
because i am able to see favicon from my side!

**Comment by SaurabhS55** [comment]
image

**Comment by BVPKARTHIKEYA** [comment]
once merge my request and let's see the deployment link if it's not working then we'll see!
let's try this!!

**Comment by BVPKARTHIKEYA** [comment]
i'm getting this as output 
image

**Pull request merged**
